-- Trustpilot data is admin-managed because Trustpilot's CloudFront WAF
-- blocks server-to-server scraping of the public review page (every
-- request from a Vercel/serverless egress IP returns 403). The two
-- workarounds are (a) buy a Trustpilot Business API key, or (b) let
-- the team curate the score and the visible reviews in Postgres. We
-- went with (b) so the score and any new reviews can be updated
-- without a code deploy.
--
-- 1. landing_manual_stats gets a `trustpilot_score_label` column so
--    the score next to "Loved on Trustpilot" stays in sync with the
--    real Trustpilot page.
-- 2. landing_trustpilot_reviews is a small editable table whose rows
--    drive the cycling reviews carousel on the homepage and pricing
--    page. Add a row when a new review lands on Trustpilot.

alter table public.landing_manual_stats
  add column if not exists trustpilot_score_label text not null default '4.7/5';

create table if not exists public.landing_trustpilot_reviews (
  id bigint primary key generated by default as identity,
  name text not null,
  body_en text not null,
  body_fr text,
  rating smallint not null default 5 check (rating between 1 and 5),
  sort_order int not null default 0,
  hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists landing_trustpilot_reviews_sort_idx
  on public.landing_trustpilot_reviews (hidden, sort_order, created_at desc);

alter table public.landing_trustpilot_reviews enable row level security;

drop policy if exists "landing_trustpilot_reviews_public_read"
  on public.landing_trustpilot_reviews;
create policy "landing_trustpilot_reviews_public_read"
on public.landing_trustpilot_reviews
for select
using (hidden = false);
