"use client";

import { useDocsLocale } from "../DocsLocaleContext";

export default function StudioDocPage() {
  const locale = useDocsLocale();

  return (
    <>
      <p className="text-[12px] tracking-wider text-[#999]">
        {locale === "fr" ? "Fonctionnalités" : "Features"}
      </p>
      <h1 className="mt-4 text-[1.75rem] font-semibold text-[#111] mb-1">
        Studio
      </h1>
      <p className="text-[15px] text-[#999] mb-8">
        {locale === "fr"
          ? "Publication automatique de vidéos sur les réseaux sociaux."
          : "Automated video posting to social platforms."}
      </p>

      {/* Overview */}
      <h2 id="overview" className="text-lg font-semibold text-[#111] mt-12 mb-3">
        {locale === "fr" ? "Vue d'ensemble" : "Overview"}
      </h2>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        {locale === "fr"
          ? "Studio génère automatiquement du contenu vidéo à partir de tes morceaux et les publie sur tes comptes de réseaux sociaux connectés selon un calendrier configurable. Au lieu de créer et d'importer manuellement des vidéos, laisse vvault gérer le pipeline de contenu."
          : "Studio auto-generates video content from your tracks and posts them to your connected social media accounts on a configurable schedule. Instead of manually creating and uploading videos, let vvault handle the content pipeline."}
      </p>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        {locale === "fr"
          ? "Configure tes intervalles de publication et ton fuseau horaire, et Studio s'occupe du reste \u2014 génération des vidéos, programmation des posts et suivi du statut de synchronisation."
          : "Configure your posting intervals and timezone, and Studio takes care of the rest \u2014 generating videos, scheduling posts, and tracking sync status."}
      </p>

      {/* Video specs */}
      <h2 id="specs" className="text-lg font-semibold text-[#111] mt-12 mb-3">
        {locale === "fr" ? "Spécifications vidéo" : "Video specs"}
      </h2>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        {locale === "fr"
          ? "Les vidéos générées par Studio utilisent les spécifications suivantes :"
          : "Videos generated by Studio use the following specifications:"}
      </p>
      <div className="mt-4 overflow-hidden rounded-xl border border-[#e5e5e5] mb-4">
        <table className="w-full border-collapse text-[13px]">
          <thead>
            <tr className="bg-[#f5f5f5]">
              <th className="border-b border-[#e5e5e5] px-3 py-2 text-left font-medium text-[#555]">
                {locale === "fr" ? "Propriété" : "Property"}
              </th>
              <th className="border-b border-[#e5e5e5] px-3 py-2 text-left font-medium text-[#555]">
                {locale === "fr" ? "Valeur" : "Value"}
              </th>
            </tr>
          </thead>
          <tbody className="text-[#666]">
            <tr>
              <td className="border-b border-[#e5e5e5] px-3 py-2">Format</td>
              <td className="border-b border-[#e5e5e5] px-3 py-2">MP4</td>
            </tr>
            <tr>
              <td className="border-b border-[#e5e5e5] px-3 py-2">{locale === "fr" ? "Résolution" : "Resolution"}</td>
              <td className="border-b border-[#e5e5e5] px-3 py-2">1280 x 720</td>
            </tr>
            <tr>
              <td className="border-b border-[#e5e5e5] px-3 py-2">{locale === "fr" ? "Fréquence d'images" : "Frame rate"}</td>
              <td className="border-b border-[#e5e5e5] px-3 py-2">30 fps</td>
            </tr>
            <tr>
              <td className="px-3 py-2">Images</td>
              <td className="px-3 py-2">{locale === "fr" ? "Images carrousel prises en charge ; la première image est utilisée comme couverture" : "Carousel images supported; first image used as cover"}</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Scheduling */}
      <h2 id="scheduling" className="text-lg font-semibold text-[#111] mt-12 mb-3">
        {locale === "fr" ? "Programmation" : "Scheduling"}
      </h2>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        {locale === "fr"
          ? "Configure ton calendrier de publication avec des paramètres d'intervalle flexibles :"
          : "Configure your posting schedule with flexible interval settings:"}
      </p>
      <ul className="text-[14px] text-[#666] mb-4 list-disc pl-5 space-y-1">
        <li>
          <strong className="text-[#444]">{locale === "fr" ? "Intervalles de publication" : "Posting intervals"}</strong> &mdash;{" "}
          {locale === "fr" ? "Définis des intervalles en minutes ou heures entre chaque publication." : "Set intervals in minutes or hours between each post."}
        </li>
        <li>
          <strong className="text-[#444]">{locale === "fr" ? "Gestion du fuseau horaire" : "Timezone-aware"}</strong> &mdash;{" "}
          {locale === "fr" ? "Toute la programmation respecte ton fuseau horaire configuré pour que les posts sortent à la bonne heure locale." : "All scheduling respects your configured timezone so posts go out at the right local time."}
        </li>
        <li>
          <strong className="text-[#444]">{locale === "fr" ? "Suivi de synchronisation" : "Sync tracking"}</strong> &mdash;{" "}
          {locale === "fr" ? "Surveille le statut de chaque publication avec des logs d'erreur détaillés en cas d'échec de synchronisation." : "Monitor the status of each post with detailed error logging if a sync fails."}
        </li>
      </ul>
      <div className="rounded-xl border-l-2 border-blue-400 bg-blue-50 p-4 text-[13px] text-[#666] mb-4">
        <strong className="text-[#444]">{locale === "fr" ? "Astuce :" : "Tip:"}</strong>{" "}
        {locale === "fr"
          ? "Commence avec des intervalles plus longs (ex. toutes les quelques heures) et ajuste en fonction des données d'engagement de ton tableau de bord analytics."
          : "Start with longer intervals (e.g., every few hours) and adjust based on engagement data from your analytics dashboard."}
      </div>

      {/* Availability */}
      <h2 id="availability" className="text-lg font-semibold text-[#111] mt-12 mb-3">
        {locale === "fr" ? "Disponibilité" : "Availability"}
      </h2>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        {locale === "fr"
          ? "Studio est exclusivement disponible sur le plan Ultra. Il n'est pas inclus dans les plans Free ou Pro."
          : "Studio is exclusively available on the Ultra plan. It is not included in Free or Pro plans."}
      </p>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        {locale === "fr" ? (
          <>
            Pour commencer avec Studio, passe au plan Ultra depuis tes paramètres de facturation à{" "}
            <a href="https://vvault.app/billing" className="text-emerald-600 underline underline-offset-2">
              vvault.app/billing
            </a>
            .
          </>
        ) : (
          <>
            To get started with Studio, upgrade to Ultra from your billing settings at{" "}
            <a href="https://vvault.app/billing" className="text-emerald-600 underline underline-offset-2">
              vvault.app/billing
            </a>
            .
          </>
        )}
      </p>
    </>
  );
}
