export default function StudioDocPage() {
  return (
    <>
      <p className="text-[12px] tracking-wider text-[#999]">
        Features
      </p>
      <h1 className="mt-4 text-[1.75rem] font-semibold text-[#111] mb-1">
        Studio
      </h1>
      <p className="text-[15px] text-[#999] mb-8">
        Automated video posting to social platforms.
      </p>

      {/* Overview */}
      <h2 id="overview" className="text-lg font-semibold text-[#111] mt-12 mb-3">
        Overview
      </h2>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        Studio auto-generates video content from your tracks and posts them to your connected social media accounts on a configurable schedule. Instead of manually creating and uploading videos, let vvault handle the content pipeline.
      </p>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        Configure your posting intervals and timezone, and Studio takes care of the rest &mdash; generating videos, scheduling posts, and tracking sync status.
      </p>

      {/* Video specs */}
      <h2 id="specs" className="text-lg font-semibold text-[#111] mt-12 mb-3">
        Video specs
      </h2>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        Videos generated by Studio use the following specifications:
      </p>
      <div className="mt-4 overflow-hidden rounded-xl border border-[#e5e5e5] mb-4">
        <table className="w-full border-collapse text-[13px]">
          <thead>
            <tr className="bg-[#f5f5f5]">
              <th className="border-b border-[#e5e5e5] px-3 py-2 text-left font-medium text-[#555]">Property</th>
              <th className="border-b border-[#e5e5e5] px-3 py-2 text-left font-medium text-[#555]">Value</th>
            </tr>
          </thead>
          <tbody className="text-[#666]">
            <tr>
              <td className="border-b border-[#e5e5e5] px-3 py-2">Format</td>
              <td className="border-b border-[#e5e5e5] px-3 py-2">MP4</td>
            </tr>
            <tr>
              <td className="border-b border-[#e5e5e5] px-3 py-2">Resolution</td>
              <td className="border-b border-[#e5e5e5] px-3 py-2">1280 x 720</td>
            </tr>
            <tr>
              <td className="border-b border-[#e5e5e5] px-3 py-2">Frame rate</td>
              <td className="border-b border-[#e5e5e5] px-3 py-2">30 fps</td>
            </tr>
            <tr>
              <td className="px-3 py-2">Images</td>
              <td className="px-3 py-2">Carousel images supported; first image used as cover</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Scheduling */}
      <h2 id="scheduling" className="text-lg font-semibold text-[#111] mt-12 mb-3">
        Scheduling
      </h2>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        Configure your posting schedule with flexible interval settings:
      </p>
      <ul className="text-[14px] text-[#666] mb-4 list-disc pl-5 space-y-1">
        <li><strong className="text-[#444]">Posting intervals</strong> &mdash; Set intervals in minutes or hours between each post.</li>
        <li><strong className="text-[#444]">Timezone-aware</strong> &mdash; All scheduling respects your configured timezone so posts go out at the right local time.</li>
        <li><strong className="text-[#444]">Sync tracking</strong> &mdash; Monitor the status of each post with detailed error logging if a sync fails.</li>
      </ul>
      <div className="rounded-xl border-l-2 border-blue-400 bg-blue-50 p-4 text-[13px] text-[#666] mb-4">
        <strong className="text-[#444]">Tip:</strong> Start with longer intervals (e.g., every few hours) and adjust based on engagement data from your analytics dashboard.
      </div>

      {/* Availability */}
      <h2 id="availability" className="text-lg font-semibold text-[#111] mt-12 mb-3">
        Availability
      </h2>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        Studio is exclusively available on the <strong className="text-[#444]">Ultra plan</strong>. It is not included in Free or Pro plans.
      </p>
      <p className="text-[14px] leading-relaxed text-[#666] mb-4">
        To get started with Studio, upgrade to Ultra from your billing settings at{" "}
        <a href="https://vvault.app/billing" className="text-emerald-600 underline underline-offset-2">
          vvault.app/billing
        </a>
        .
      </p>
    </>
  );
}
